package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
)

func main() {
	cssPath := flag.String("css", "", "CSS file to embed")
	outPath := flag.String("out", "", "TypeScript output file")
	flag.Parse()

	if *cssPath == "" || *outPath == "" {
		fmt.Fprintln(os.Stderr, "usage: fernstyles --css <file> --out <file>")
		os.Exit(2)
	}

	css, err := os.ReadFile(*cssPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read css: %v\n", err)
		os.Exit(1)
	}

	encoded, err := json.Marshal(string(css))
	if err != nil {
		fmt.Fprintf(os.Stderr, "encode css: %v\n", err)
		os.Exit(1)
	}

	content := fmt.Sprintf("// Code generated by make gen; DO NOT EDIT.\n\nexport const kubectlDocStyles = %s;\n", encoded)
	if err := os.WriteFile(*outPath, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write styles: %v\n", err)
		os.Exit(1)
	}
}
