package web

import (
	"bytes"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

func TestFernComponentRuntimeAssetsStaySynced(t *testing.T) {
	t.Run("runtime", func(t *testing.T) {
		assertSynced(t, "assets/kubectl-doc.js", "../../../fern/components/kubectl-doc/kubectl-doc-runtime.js")
	})

	t.Run("css", func(t *testing.T) {
		src, err := os.ReadFile("assets/kubectl-doc.css")
		if err != nil {
			t.Fatalf("read source CSS: %v", err)
		}
		dst, err := os.ReadFile("../../../fern/components/kubectl-doc/kubectl-doc-styles.ts")
		if err != nil {
			t.Fatalf("read generated Fern styles: %v", err)
		}

		encoded, ok := strings.CutPrefix(string(dst), "// Code generated by make gen; DO NOT EDIT.\n\nexport const kubectlDocStyles = ")
		if !ok {
			t.Fatalf("generated Fern styles have unexpected prefix:\n%s", dst)
		}
		encoded = strings.TrimSuffix(encoded, ";\n")
		var decoded string
		if err := json.Unmarshal([]byte(encoded), &decoded); err != nil {
			t.Fatalf("decode generated Fern styles: %v", err)
		}
		if !bytes.Equal(src, []byte(decoded)) {
			t.Fatalf("generated Fern styles are not synced with assets/kubectl-doc.css; run make gen")
		}
	})
}

func assertSynced(t *testing.T, srcPath, dstPath string) {
	t.Helper()

	src, err := os.ReadFile(srcPath)
	if err != nil {
		t.Fatalf("read source asset: %v", err)
	}
	dst, err := os.ReadFile(dstPath)
	if err != nil {
		t.Fatalf("read Fern component asset: %v", err)
	}
	if !bytes.Equal(src, dst) {
		t.Fatalf("Fern component asset %s is not synced with %s; run make gen", dstPath, srcPath)
	}
}
