package web

import (
	"bytes"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

func TestReactComponentStyleAssetStaysSynced(t *testing.T) {
	t.Run("css", func(t *testing.T) {
		src, err := os.ReadFile("assets/kubectl-doc.css")
		if err != nil {
			t.Fatalf("read source CSS: %v", err)
		}
		dst, err := os.ReadFile("../../../react/kubectl-doc/kubectl-doc-styles.ts")
		if err != nil {
			t.Fatalf("read generated React styles: %v", err)
		}

		encoded, ok := strings.CutPrefix(string(dst), "// Code generated by make gen; DO NOT EDIT.\n\nexport const kubectlDocStyles = ")
		if !ok {
			t.Fatalf("generated React styles have unexpected prefix:\n%s", dst)
		}
		encoded = strings.TrimSuffix(encoded, ";\n")
		var decoded string
		if err := json.Unmarshal([]byte(encoded), &decoded); err != nil {
			t.Fatalf("decode generated React styles: %v", err)
		}
		if !bytes.Equal(src, []byte(decoded)) {
			t.Fatalf("generated React styles are not synced with assets/kubectl-doc.css; run make gen")
		}
	})
}
